version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  pdf-api:
    build:
      context: ./pdf-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    restart: always
